#!/usr/bin/env node

const L = require('./lib').logger;
const responseLogger = require('./lib').responseLogger;
const dictionaryApi = require('./api').dictionary;
const logtag = '[dict]';

(async function () {
    let command = process.argv[2];
    let word = process.argv[3];

    try {
        let response = {};

        switch (command) {
            case 'defn':
                response = await dictionaryApi.getWordDefinition(word);
                break;
            case 'syn':
                response = await dictionaryApi.getRelatedWords(word, 'synonym');
                break;
            case 'ant':
                response = await dictionaryApi.getRelatedWords(word, 'antonym');
                break;
            case 'ex':
                response = await dictionaryApi.getWordExamples(word);
                break;
            case 'play':
                await dictionaryApi.gameplay();
                break;
            case undefined:
                randomWordResponse = await dictionaryApi.getRandomWord();
                word = randomWordResponse && randomWordResponse.word;
                response = await dictionaryApi.getAll(word);
                break;
            default:
                word = command;
                response = await dictionaryApi.getAll(word);
                break;

        }

        responseLogger(command, response);

        process.exit(0);
    } catch (err) {
        L.error(`${logtag} : Error occurred :`, (err && err.message) || err);
        process.exit(1);
    }
}())